# Generated by Django 4.2 on 2024-09-19 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0003_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="saved",
            field=models.ManyToManyField(
                blank=True, related_name="saved_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
