# Generated by Django 4.2 on 2024-09-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_saved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="saved",
            new_name="saved_by",
        ),
    ]
